default: &default
  adapter: postgresql
  encoding: unicode
  #host: uniquebrotherprod.cqfyy837hf53.us-east-2.rds.amazonaws.com
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST_URL")%>
  port: 5432
  username: postgres
  #password: <%= ENV.fetch("DATABASE_PASSWORD") { 5 } %> 

development:
  <<: *default
  database: unique_brother_development
  #username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %> 

test:
  <<: *default
  database: unique_brother_test
  #username: postgres
  password: <%= ENV.fetch("DATABASE_PASSWORD") %> 

production:
  <<: *default
  database: unique_brother_production 
  #username: postgres
  password: <%= ENV.fetch("DATABASE_PASSWORD") %> 


